#!/bin/bash

# Write current chapter to logbook

if [ $# -ne 1 ]
then
  echo Usage: wlog string
  echo "   Appends string to logbook."
  exit 1
fi

echo $(date +"%Y-%m-%d") $1 >> log

echo Done.

tail log
exit 0
